FROM python:3.11-slim

WORKDIR /app

ENV PYTHONUNBUFFERED=1 \
    PYTHONDONTWRITEBYTECODE=1 \
    PIP_NO_CACHE_DIR=1 \
    PIP_DISABLE_PIP_VERSION_CHECK=1

COPY requirements.txt .
RUN pip install --default-timeout=120 -r requirements.txt

COPY . .
RUN chmod +x docker-entrypoint.sh
EXPOSE 8000

CMD ["./docker-entrypoint.sh"]
