"""add ambitionbox fields to companies

Revision ID: 8b1885354f01
Revises: c42229806df9
Create Date: 2026-09-05 18:53:40.422765

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '8b1885354f01'
down_revision: Union[str, Sequence[str], None] = 'c42229806df9'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    # server_default is required here: the companies table already has rows
    # (production has been caching lookups since the last release), and a
    # NOT NULL column added to a populated table needs a fill-in value.
    op.add_column('companies', sa.Column('classification', sa.Text(), nullable=False, server_default=''))
    op.add_column('companies', sa.Column('ambitionbox_rating', sa.Float(), nullable=True))
    op.add_column('companies', sa.Column('ambitionbox_reviews_count', sa.Integer(), nullable=True))
    op.add_column('companies', sa.Column('ambitionbox_job_profiles', postgresql.JSONB(astext_type=sa.Text()), nullable=False, server_default='[]'))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('companies', 'ambitionbox_job_profiles')
    op.drop_column('companies', 'ambitionbox_reviews_count')
    op.drop_column('companies', 'ambitionbox_rating')
    op.drop_column('companies', 'classification')
    # ### end Alembic commands ###
